### PR TITLE
diffusion models related paper

### PR DESCRIPTION
**Pull request by talbenha**
add dreambooth paper

### CODE REVIEW

**Comment by talbenha** [comment]
@SkalskiP please approve
dreambooth is one of the most famous papers this year that propose a new approach for fine-tuning text to image diffusion models

**Comment by SkalskiP** [comment]
Hi 👋🏻 I changed the repository structure and couldn't merge your PR without many changes, so it was easier to commit my changes straight to master. Nevertheless, thanks a lot for the great suggestions. 🙏🏻 

Here is the change I made: https://github.com/SkalskiP/top-cvpr-2023-papers/commit/1881d9752ce80f2f6b08a76c284640f8ba62c639

**Comment by talbenha** [comment]
@SkalskiP The changes you made are very minor- you only needed to remove three '|' to merge my PR. You could ask me for the changes..
Very disappointing behaviour to take my contribution and merge it without any credit!

**Comment by talbenha** [comment]
you also have some mistakes in the change you made-  LMK if you want me to change it with merging MY PR.

**Comment by SkalskiP** [comment]
Hi 👋🏻 @talbenha! I see you got angry at me. I’m super sorry to see that. That was not what I wanted to cause. I’m currently on CVPR and don’t have a lot of time for maintenance:/ I just did something quickly.

> The changes you made are very minor- you only needed to remove three '|' to merge my PR. You could ask me for the changes..
Very disappointing behaviour to take my contribution and merge it without any credit!

Actually the change is much bigger. The table is now build automatically I don’t update it manually. There is automation directory in repo now.

**Comment by SkalskiP** [comment]
As for mistakes. If you see any mistakes feel free to open PR. I promise I’ll merge it.

**Pull request closed without merging**
