### PR TITLE
add two papers (SFD2, IMP)

### PR DESCRIPTION
**Pull request by feixue94**

### CODE REVIEW

**Comment by SkalskiP** [comment]
Hi @feixue94 👋🏻 Why you decided to close the PR?

**Comment by feixue94** [comment]
Hi @SkalskiP , this PR has been here for over 3 weeks. Although I think these two papers are very interesting in particular for the task of feature matching and long-term localization in 3D scene understanding, they might not be of your interest, so I closed it. Do you want me to reopen it?

**Comment by SkalskiP** [comment]
Hi, @feixue94 👋🏻! The main point is that these papers go beyond my domain. And I just don't consider myself qualified enough to judge them.

**Comment by feixue94** [comment]
Hi @SkalskiP Thanks for the reply. I will close it temporally.

**Pull request closed without merging**
